script: src/main/resources/echo.sh

onlyUseScriptArgs: false

emailConfiguration:
    user: hedgie@dash.by
    password: unknown
    smtpHost: smtp.gmail.com
    smtpPort: 465

failureSubjectPrefix: FAILURE echoing

failureBodyPrefix: Could not echo

failureEmail: commiters@dash.by

logging:
    level: INFO
    loggers:
        "com.dashlabs": INFO
    appenders:
        - type: console
          threshold: ALL
          timeZone: UTC
          target: stdout
        - type: file
          threshold: ALL
          currentLogFilename: /tmp/octoreceiver.log
          archivedLogFilenamePattern: /tmp/octoreceiver-%d.log.gz
          archivedFileCount: 5
          timeZone: UTC

server:
    type: default
    gzip:
        bufferSize: 8KiB
    applicationConnectors:
        - type: http
          port: 8081
    adminConnectors:
        - type: http
          port: 8082
    requestLog:
        timeZone: UTC
        appenders:
            - type: file
              threshold: ALL
              currentLogFilename: /tmp/http-octoreceiver.log
              archivedLogFilenamePattern: /tmp/http-octoreceiver-%d.log.gz
              archivedFileCount: 5
              timeZone: UTC